spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://db:5432/votingapplication
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234


logging:
  level:
      org: error

roles:
  admin: ADMIN
  user: USER

auth-whitelist:
  /token-refresh,
  /register,
  /login,
  /v2/api-docs,
  /swagger-resources,
  /swagger-resources/**,
  /configuration/ui,
  /configuration/security,
  /swagger-ui.html,
  /webjars/**,
  /v3/api-docs/**,
  /swagger-ui/**
#  /users,
#  /usernames,
#  /userId/**,
#  /users-group/add,
#  /users-group/edit,
#  /user-group/**,
#  /user-group/delete/**,
#  /voting/add,
#  /voting/**,
#  /voting/forUser/**,
#  /voting/delete/**,
#  /voting-edit,
#  /deactivate-voting/**,
#  /shareToUsers,
#  /sharedUsers/**,
#  /votingSharedToUser/**,
#  /vote,
#  /voting-result/**,
#  /voting/get-token/**,

permits:
  user:
    /users,
    /usernames,
    /userId/**,
    /users-group/add,
    /users-group/edit,
    /user-group/**,
    /user-group/delete/**,
    /voting/add,
    /voting/**,
    /voting/forUser/**,
    /voting/delete/**,
    /voting-edit,
    /deactivate-voting/**,
    /shareToUsers,
    /sharedUsers/**,
    /votingSharedToUser/**,
    /vote,
    /voting-result/**,
    /voting/get-token/**

  admin:
    /users/add
server:
  port: 8180
