version: '3.8'

services:
  backend-app:
    image: 'voting-application-backend'
    build: ./../../../
    container_name: backend-app
    ports:
      - "8180:8180"
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./../resources/db/initDB/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: frontend-container
    build: ./../../../../VotingApplicationFrontend
    volumes:
      - './../../../../VotingApplicationFrontend:/usr/src/app'
    ports:
      - "4200:4200"
    command: >
      bash -c "npm start"
