services:
  backend-app:
    image: 'voting-application-backend'
    build: ./../../../
    container_name: backend-application
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234