CREATE TABLE answers
(
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer    VARCHAR(255)                            NOT NULL,
    voting_id BIGINT,
    CONSTRAINT answers_pkey PRIMARY KEY (answer_id)
);

CREATE TABLE roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE user_group
(
    user_group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_group_name VARCHAR(255)                            NOT NULL,
    owner_id        BIGINT,
    CONSTRAINT user_group_pkey PRIMARY KEY (user_group_id)
);

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN DEFAULT TRUE                    NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE voting_results
(
    voting_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer_id        BIGINT,
    user_id          BIGINT,
    voting_id        BIGINT,
    CONSTRAINT voting_results_pkey PRIMARY KEY (voting_result_id)
);

CREATE TABLE votings
(
    voting_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    explicit    BOOLEAN                                 NOT NULL,
    question    VARCHAR(255)                            NOT NULL,
    restricted  BOOLEAN                                 NOT NULL,
    voting_name VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    CONSTRAINT votings_pkey PRIMARY KEY (voting_id)
);

CREATE TABLE user_group_users
(
    user_group_user_group_id BIGINT NOT NULL,
    users_user_id            BIGINT NOT NULL
);

CREATE TABLE users_roles
(
    users_user_id BIGINT NOT NULL,
    roles_role_id BIGINT NOT NULL
);

CREATE TABLE votings_shared_to_users
(
    votings_voting_id       BIGINT NOT NULL,
    shared_to_users_user_id BIGINT NOT NULL
);

ALTER TABLE votings
    ADD CONSTRAINT fk2y02omj34swgyq57t9rcnpq6w FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE voting_results
    ADD CONSTRAINT fk4w9293siop04cw88n9l92b2by FOREIGN KEY (answer_id) REFERENCES answers (answer_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_group
    ADD CONSTRAINT fk7c9ns1xpd8armd4b011lbyv6u FOREIGN KEY (owner_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE voting_results
    ADD CONSTRAINT fk9qucwpfaayf6kjp0ksh1qfrr8 FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE votings_shared_to_users
    ADD CONSTRAINT fkbeacp2as7hv9b7yv0laxx4m08 FOREIGN KEY (votings_voting_id) REFERENCES votings (voting_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE answers
    ADD CONSTRAINT fkicy9ww3r6nng5kakt9na3u7f9 FOREIGN KEY (voting_id) REFERENCES votings (voting_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_group_users
    ADD CONSTRAINT fkku3fyvg07lipyw5sr4io2isn9 FOREIGN KEY (user_group_user_group_id) REFERENCES user_group (user_group_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_group_users
    ADD CONSTRAINT fkm080xk3yrmj8y6h05rdrhy6k6 FOREIGN KEY (users_user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE votings_shared_to_users
    ADD CONSTRAINT fkm26ywob1g3p478pn3f57rdfx7 FOREIGN KEY (shared_to_users_user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_roles
    ADD CONSTRAINT fkmaps3ffbyjaxkt50q1c7s7v5j FOREIGN KEY (users_user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE voting_results
    ADD CONSTRAINT fkmfpu4tyekbil0f412ktytllki FOREIGN KEY (voting_id) REFERENCES votings (voting_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_roles
    ADD CONSTRAINT fktgou1kvdhyryu3fia6uu1fhoi FOREIGN KEY (roles_role_id) REFERENCES roles (role_id) ON UPDATE NO ACTION ON DELETE NO ACTION;