CREATE TABLE answers
(
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer    VARCHAR(255)                            NOT NULL,
    voting_id BIGINT,
    CONSTRAINT pk_answers PRIMARY KEY (answer_id)
);

CREATE TABLE roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE user_group
(
    user_group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id        BIGINT,
    user_group_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_usergroup PRIMARY KEY (user_group_id)
);

CREATE TABLE user_group_users
(
    user_group_user_group_id BIGINT NOT NULL,
    users_user_id            BIGINT NOT NULL
);

CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_keycloak_id VARCHAR(255)                            NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE voting_results
(
    voting_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    answer_id        BIGINT,
    voting_id        BIGINT,
    CONSTRAINT pk_votingresults PRIMARY KEY (voting_result_id)
);

CREATE TABLE votings
(
    voting_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    voting_name VARCHAR(255)                            NOT NULL,
    question    VARCHAR(255)                            NOT NULL,
    restricted  BOOLEAN                                 NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    explicit    BOOLEAN                                 NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT,
    CONSTRAINT pk_votings PRIMARY KEY (voting_id)
);

CREATE TABLE votings_shared_to_users
(
    votings_voting_id       BIGINT NOT NULL,
    shared_to_users_user_id BIGINT NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT user_username_unique UNIQUE (username);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_VOTING FOREIGN KEY (voting_id) REFERENCES votings (voting_id);

ALTER TABLE user_group
    ADD CONSTRAINT FK_USERGROUP_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id);

ALTER TABLE voting_results
    ADD CONSTRAINT FK_VOTINGRESULTS_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answers (answer_id);

ALTER TABLE voting_results
    ADD CONSTRAINT FK_VOTINGRESULTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE voting_results
    ADD CONSTRAINT FK_VOTINGRESULTS_ON_VOTING FOREIGN KEY (voting_id) REFERENCES votings (voting_id);

ALTER TABLE votings
    ADD CONSTRAINT FK_VOTINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_group_users
    ADD CONSTRAINT fk_usegrouse_on_user FOREIGN KEY (users_user_id) REFERENCES users (user_id);

ALTER TABLE user_group_users
    ADD CONSTRAINT fk_usegrouse_on_user_group FOREIGN KEY (user_group_user_group_id) REFERENCES user_group (user_group_id);

ALTER TABLE votings_shared_to_users
    ADD CONSTRAINT fk_votshatouse_on_user FOREIGN KEY (shared_to_users_user_id) REFERENCES users (user_id);

ALTER TABLE votings_shared_to_users
    ADD CONSTRAINT fk_votshatouse_on_voting FOREIGN KEY (votings_voting_id) REFERENCES votings (voting_id);